### ISSUE TITLE
[Bug] Crash engine: paste command after removing in object command

### ISSUE THREAD

**Issue by Wano-k** [RPG-Paper-Maker/RPG-Paper-Maker#25]

**Comment by hsandt** [comment]
I tried to repro and realized I can indeed crash the engine, but not because I am pasting a deleted command as I first thought, but because selection is nullptr.
Indeed, copyCommand does copy the current selection into a buffer, so there is no issue with pasting a command that has been deleted: we hold a completely different copy of it in memory.
So I will give the repro and suggested fix for the bug: "Crash in Object... window when pasting command while selection is empty".
If you feel that there is another bug hiding, add it in comment with the repro or open a new issue if I have already closed this one.

Repro:
1. Create new Object or edit Object
2. Click inside the action[] pane, but without selecting a command
3. Paste a command (ctrl+v). Even if you haven't copied anything first.

Result:
SIGSEGV in WidgetTreeCommands::getRootOfCommand

Quick fix:
If WidgetTreeCommands::pasteCommand is called with selected == nullptr, ignore and return.
Pasting a deleted command will not do anything, as if nothing was copied. Check if we need feedback.
Note that this counts on Qt cleaning up old data

Alternative fix:
Add command to the end of the list of commands, if you think that makes sense

Assignment:
Will try to fix it today

**Comment by hsandt** [comment]
OK, found a fix, but discovered other crashes related to selected == nullptr elsewhere. Trying to refacto all of that.

Also trying to understand why Enter sometimes edit, sometimes add new command in `WidgetTreeCommands::keyPressEvent` (apparently the action may be enabled or disabled, see `action->isEnabled()`). One of my fixes will do nothing when trying to `contextEdit` an entry if selected is nullptr, but I wonder if I shouldn't return a Success bool value in this case so `keyPressEvent` knows it shouldn't consume the event and try the next shortcut (in other words, if we find nothing to Edit, we should Add a new command). But it also seems that it's a bug that the Edit action is active when there is no selection anyway, so should we handle a case that is a bug?

My commits are not clean enough for a PR, but you can already check them at https://github.com/hsandt/RPG-Paper-Maker/commits/feature/fix-commands-no-selection-crash.

Do you prefer that I solve one problem at a time or that I prepare a big PR that solves all the nullptr selected & Enter key handling issue?

**Comment by Wano-k** [comment]
I merged the PR, but you can continue to clear the fixes in the same one! Thanks for correcting the selection issue, I also noticed that something was wrong with the no selection nullptr. If you could handle the issue with Enter Add / Edit that would be great. :)

Thanks!

**Comment by hsandt** [comment]
OK, in the meantime I opened the issue you see just above with more details, so you should close this one (you are the actual author so I can't close it myself).
